# .github/workflows/ci.yml
name: CI
defaults:
  run:
    shell: bash -ieo pipefail {0}

    
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: "pycram/semantic_world:jazzy"
    steps:
    - uses: actions/checkout@v4
      with:
        path: "ros/src/semantic_world"
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        submodules: 'false'
    - name: Update semantic_world source files
      run: |
        rm -rf /opt/ros/semantic_world/* 
        cd /opt/ros//semantic_world
        rm -rf .git .github .gitignore .gitmodules .readthedocs.yaml
        cp -r /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/ros/src/semantic_world /opt/ros/

    - name: Install dependencies
      run: |
        sudo apt-get update
        cd /opt/ros/semantic_world
        source /opt/ros/semantic_world-venv/bin/activate
        git submodule init
        git submodule update
        pip install -U pip && pip install -r requirements.txt && pip install -e . && pip install pytest
        if [[ $(python3 --version) == "Python 3.10"* ]]; then
          PACKAGE_URL="https://nc.uni-bremen.de/public.php/dav/files/fxWQigKXPBtnXsy/?accept=zip"
          PACKAGE_HASH="5249b21f6a6dbbb86eee9e64659cf19b9b09585ffbc888d13af9bd9c2bcce99c"
        elif [[ $(python3 --version) == "Python 3.12"* ]]; then
          PACKAGE_URL="https://nc.uni-bremen.de/public.php/dav/files/nxxi4QSBcYmmxba/?accept=zip"
          PACKAGE_HASH="a111ac524d6eb9161ed90972cd60670de887066b553a91a397da985f3a60f9aa"
        fi
        if [[ -n "$PACKAGE_URL" ]]; then
          TMP_PKG="/tmp/secure_pkg.zip"
          curl -fsSL "$PACKAGE_URL" -o "$TMP_PKG"
          echo "$PACKAGE_HASH  $TMP_PKG" | sha256sum -c -
          pip install "$TMP_PKG"
          rm -f "$TMP_PKG"
        fi
        pip install -e ./src/ripple_down_rules_meta
#        echo "PATH=/opt/ros/overlay_ws/src/Multiverse-Parser/ext/blender:/opt/ros/overlay_ws/src/Multiverse-Parser/USD/linux/lib/python:/opt/ros/overlay_ws/src/Multiverse-Parser/USD/linux/plugin/usd:$PATH" >> $GITHUB_ENV
#        echo "PYTHONPATH=/opt/ros/overlay_ws/src/Multiverse-Parser/USD/linux/lib/python:/opt/ros/overlay_ws/src/src" >> $GITHUB_ENV


    - name: Run tests
      run: |
        source /opt/ros/overlay_ws/install/setup.bash
        source /opt/ros/semantic_world-venv/bin/activate
        cd /opt/ros/semantic_world
        python -m pytest -v test/
